"use client";

import {useState} from "react";
import UserReportForm from "./UserReportForm";

type RawEvent = {
  id: number;
  source: string;
  category:
    | "weather"
    | "transportation"
    | "building"
    | "power"
    | "network"
    | "user_report";
  title: string;
  message: string;
  location_name: string;
  latitude: number;
  longitude: number;
  timestamp: string;
  severity: "low" | "medium" | "high";
  status: string;
};

type Incident = {
  id: number;
  title: string;
  summary: string;
  severity: "low" | "medium" | "high";
  status: "active" | "monitoring" | "resolved";
  affected_area: string;
  recommended_action: string;
  evidence_event_ids: number[];
};


type CategoryFilter = RawEvent["category"] | "all";
type SeverityFilter = RawEvent["severity"] | "all";

type EventDashboardProps = {
  events: RawEvent[];
  incidents: Incident[];
};

function getSeverityStyles(severity: RawEvent["severity"]) {
  if (severity === "high") {
    return "border-red-400/40 bg-red-500/10 text-red-300";
  }

  if (severity === "medium") {
    return "border-yellow-400/40 bg-yellow-500/10 text-yellow-200";
  }

  return "border-green-400/40 bg-green-500/10 text-green-300";
}

function getCategoryLabel(category: RawEvent["category"]) {
  const labels = {
    weather: "Weather",
    transportation: "Transportation",
    building: "Building",
    power: "Power",
    network: "Network",
    user_report: "User Report",
  };

  return labels[category];
}

function getFilterButtonStyles(isActive: boolean) {
  if (isActive) {
    return "border-cyan-400 bg-cyan-500/20 text-cyan-100";
  }

  return "border-white/10 bg-white/5 text-slate-300 hover:border-cyan-400/50 hover:bg-cyan-500/10";
}

function getEvidenceEvents(incident: Incident, events: RawEvent[]) {
  return events.filter((event) =>
    incident.evidence_event_ids.includes(event.id) //keep events whose ids are listed in the incident evidence ids
  );
}


export default function EventDashboard({
  events,
  incidents,
}: EventDashboardProps) {
  const [dashboardEvents, setDashboardEvents] = useState<RawEvent[]>(events);
  // set function lets change the state of the current incidents 
  // to update incidents card whemn user reports sth 
  const [dashboardIncidents, setDashboardIncidents] = useState<Incident[]>(incidents);

  const [selectedCategory, setSelectedCategory] =
    useState<CategoryFilter>("all");

  const [selectedSeverity, setSelectedSeverity] =
    useState<SeverityFilter>("all");
  
  
  async function refreshIncidents() {
    try {
      const response = await fetch("http://127.0.0.1:8000/incidents", { // get last generated incidents 
        cache: "no-store",
      });

      if (!response.ok) {
        return;
      }

      const updatedIncidents: Incident[] = await response.json(); // turning backend JSON into frontend Javascript usable data

      setDashboardIncidents(updatedIncidents); //update incident card
    } catch {
      return;
    }
  }

  const filteredEvents = dashboardEvents.filter((event) => {
    const categoryMatches =
      selectedCategory === "all" || event.category === selectedCategory;

    const severityMatches =
      selectedSeverity === "all" || event.severity === selectedSeverity;

    return categoryMatches && severityMatches;
  });

  return (
    <>
      <UserReportForm
        onReportCreated={(newEvent) => {
          setDashboardEvents((currentEvents) => [newEvent, ...currentEvents]); // update raw events rigth away
          setSelectedCategory("all");
          setSelectedSeverity("all");
          refreshIncidents(); // ask backend to generate incidents usign updated event list
        }}
      />

      <section className="mb-10">
        <div className="mb-5">
          <h2 className="text-2xl font-bold">Generated Incidents</h2>
          <p className="mt-1 text-sm text-slate-400">
            These incidents are generated by grouping related raw signals and
            attaching the supporting evidence.
          </p>
        </div>

        {dashboardIncidents.length === 0 ? (
          <div className="rounded-2xl border border-white/10 bg-white/5 p-8 text-center">
            <h3 className="text-xl font-semibold">No incidents generated</h3>
            <p className="mt-2 text-sm text-slate-400">
              More raw signals may be needed before the system can detect a
              larger incident.
            </p>
          </div>
        ) : (
          <div className="grid gap-4">
            {dashboardIncidents.map((incident) => {
              const evidenceEvents = getEvidenceEvents(
                incident,
                dashboardEvents
              );

              return (
                <article
                  key={incident.id}
                  className="rounded-2xl border border-white/10 bg-white/5 p-6 shadow-lg shadow-black/20"
                >
                  <div className="mb-4 flex flex-wrap items-center justify-between gap-3">
                    <span className="rounded-full border border-purple-400/30 bg-purple-500/10 px-3 py-1 text-xs font-medium text-purple-200">
                      Generated Incident
                    </span>

                    <span
                      className={`rounded-full border px-3 py-1 text-xs font-medium ${getSeverityStyles(
                        incident.severity
                      )}`}
                    >
                      {incident.severity.toUpperCase()}
                    </span>
                  </div>

                  <h3 className="mb-2 text-xl font-semibold">
                    {incident.title}
                  </h3>

                  <p className="mb-5 text-sm leading-6 text-slate-300">
                    {incident.summary}
                  </p>

                  <div className="grid gap-4 text-sm sm:grid-cols-3">
                    <div>
                      <p className="text-slate-500">Affected Area</p>
                      <p className="text-slate-200">
                        {incident.affected_area}
                      </p>
                    </div>

                    <div>
                      <p className="text-slate-500">Status</p>
                      <p className="text-slate-200">{incident.status}</p>
                    </div>

                    <div>
                      <p className="text-slate-500">Evidence Count</p>
                      <p className="text-slate-200">
                        {evidenceEvents.length} raw events
                      </p>
                    </div>
                  </div>

                  <div className="mt-5 rounded-xl border border-cyan-400/20 bg-cyan-500/10 p-4">
                    <p className="mb-1 text-sm font-semibold text-cyan-200">
                      Recommended Action
                    </p>
                    <p className="text-sm leading-6 text-slate-300">
                      {incident.recommended_action}
                    </p>
                  </div>

                  <div className="mt-5">
                    <p className="mb-3 text-sm font-semibold text-slate-300">
                      Supporting Evidence
                    </p>

                    <div className="grid gap-2">
                      {evidenceEvents.map((event) => (
                        <div
                          key={event.id}
                          className="rounded-xl border border-white/10 bg-slate-950/60 p-3"
                        >
                          <div className="flex flex-wrap items-center justify-between gap-2">
                            <p className="font-medium text-slate-200">
                              #{event.id} · {event.title}
                            </p>
                            <span className="text-xs text-slate-500">
                              {getCategoryLabel(event.category)}
                            </span>
                          </div>

                          <p className="mt-1 text-sm text-slate-400">
                            {event.message}
                          </p>
                        </div>
                      ))}
                    </div>
                  </div>
                </article>
              );
            })}
          </div>
        )}
      </section>

      <div className="mb-6 flex flex-col gap-4">
        <div>
          <h2 className="text-2xl font-bold">Live Raw Signals</h2>
          <p className="mt-1 text-sm text-slate-400">
            These are the unprocessed alerts, reports, and operational signals
            coming into the system.
          </p>
        </div>

        <div className="rounded-2xl border border-white/10 bg-white/5 p-5">
          <p className="mb-3 text-sm font-semibold text-slate-300">
            Filter by category
          </p>

          <div className="flex flex-wrap gap-2">
            <button
              onClick={() => setSelectedCategory("all")}
              className={`rounded-full border px-4 py-2 text-sm transition ${getFilterButtonStyles(
                selectedCategory === "all"
              )}`}
            >
              All
            </button>

            <button
              onClick={() => setSelectedCategory("weather")}
              className={`rounded-full border px-4 py-2 text-sm transition ${getFilterButtonStyles(
                selectedCategory === "weather"
              )}`}
            >
              Weather
            </button>

            <button
              onClick={() => setSelectedCategory("transportation")}
              className={`rounded-full border px-4 py-2 text-sm transition ${getFilterButtonStyles(
                selectedCategory === "transportation"
              )}`}
            >
              Transportation
            </button>

            <button
              onClick={() => setSelectedCategory("building")}
              className={`rounded-full border px-4 py-2 text-sm transition ${getFilterButtonStyles(
                selectedCategory === "building"
              )}`}
            >
              Building
            </button>

            <button
              onClick={() => setSelectedCategory("power")}
              className={`rounded-full border px-4 py-2 text-sm transition ${getFilterButtonStyles(
                selectedCategory === "power"
              )}`}
            >
              Power
            </button>

            <button
              onClick={() => setSelectedCategory("network")}
              className={`rounded-full border px-4 py-2 text-sm transition ${getFilterButtonStyles(
                selectedCategory === "network"
              )}`}
            >
              Network
            </button>

            <button
              onClick={() => setSelectedCategory("user_report")}
              className={`rounded-full border px-4 py-2 text-sm transition ${getFilterButtonStyles(
                selectedCategory === "user_report"
              )}`}
            >
              User Reports
            </button>
          </div>
        </div>

        <div className="rounded-2xl border border-white/10 bg-white/5 p-5">
          <p className="mb-3 text-sm font-semibold text-slate-300">
            Filter by severity
          </p>

          <div className="flex flex-wrap gap-2">
            <button
              onClick={() => setSelectedSeverity("all")}
              className={`rounded-full border px-4 py-2 text-sm transition ${getFilterButtonStyles(
                selectedSeverity === "all"
              )}`}
            >
              All
            </button>

            <button
              onClick={() => setSelectedSeverity("high")}
              className={`rounded-full border px-4 py-2 text-sm transition ${getFilterButtonStyles(
                selectedSeverity === "high"
              )}`}
            >
              High
            </button>

            <button
              onClick={() => setSelectedSeverity("medium")}
              className={`rounded-full border px-4 py-2 text-sm transition ${getFilterButtonStyles(
                selectedSeverity === "medium"
              )}`}
            >
              Medium
            </button>

            <button
              onClick={() => setSelectedSeverity("low")}
              className={`rounded-full border px-4 py-2 text-sm transition ${getFilterButtonStyles(
                selectedSeverity === "low"
              )}`}
            >
              Low
            </button>
          </div>
        </div>

        <p className="text-sm text-slate-400">
          Showing{" "}
          <span className="font-semibold text-slate-200">
            {filteredEvents.length}
          </span>{" "}
          of{" "}
          <span className="font-semibold text-slate-200">
            {dashboardEvents.length}
          </span>{" "}
          events.
        </p>
      </div>

      {filteredEvents.length === 0 ? (
        <div className="rounded-2xl border border-white/10 bg-white/5 p-8 text-center">
          <h3 className="text-xl font-semibold">No matching events</h3>
          <p className="mt-2 text-sm text-slate-400">
            Try changing the category or severity filter.
          </p>
        </div>
      ) : (
        <div className="grid gap-4 md:grid-cols-2">
          {filteredEvents.map((event) => (
            <article
              key={event.id}
              className="rounded-2xl border border-white/10 bg-white/5 p-6 shadow-lg shadow-black/20"
            >
              <div className="mb-4 flex flex-wrap items-center justify-between gap-3">
                <span className="rounded-full border border-cyan-400/30 bg-cyan-500/10 px-3 py-1 text-xs font-medium text-cyan-200">
                  {getCategoryLabel(event.category)}
                </span>

                <span
                  className={`rounded-full border px-3 py-1 text-xs font-medium ${getSeverityStyles(
                    event.severity
                  )}`}
                >
                  {event.severity.toUpperCase()}
                </span>
              </div>

              <h3 className="mb-2 text-xl font-semibold">{event.title}</h3>

              <p className="mb-5 text-sm leading-6 text-slate-300">
                {event.message}
              </p>

              <div className="grid gap-3 text-sm text-slate-400 sm:grid-cols-2">
                <div>
                  <p className="text-slate-500">Location</p>
                  <p className="text-slate-200">{event.location_name}</p>
                </div>

                <div>
                  <p className="text-slate-500">Source</p>
                  <p className="text-slate-200">{event.source}</p>
                </div>

                <div>
                  <p className="text-slate-500">Status</p>
                  <p className="text-slate-200">{event.status}</p>
                </div>

                <div>
                  <p className="text-slate-500">Timestamp</p>
                  <p className="text-slate-200">{event.timestamp}</p>
                </div>
              </div>
            </article>
          ))}
        </div>
      )}
    </>
  );
}