from app.models import RawEvent

MOCK_EVENTS = [
    RawEvent(
        id = 1,
        source = "weather_api",
        category = "weather",
        title = " Heavy Rain Alert",
        message = "Heavy rain is expected near campus between 3 PM and 6 PM.",
        location_name = "North Campus",
        latitude = 42.8172,
        longitude= -73.9301,
        timestamp="2026-06-27T15:00:00",
        severity="medium",
        status="active",
    ),
    RawEvent(
        id=2,
        source="campus_transportation",
        category="transportation",
        title="Shuttle Delay",
        message="Route B shuttle is delayed by approximately 25 minutes.",
        location_name="Main Gate",
        latitude=42.8190,
        longitude=-73.9290,
        timestamp="2026-06-27T15:12:00",
        severity="medium",
        status="active",
    ),
    RawEvent(
        id=3,
        source="student_report",
        category="user_report",
        title="Flooding Near Dorms",
        message="A student reported water pooling near the north dorm entrance.",
        location_name="North Dorms",
        latitude=42.8184,
        longitude=-73.9312,
        timestamp="2026-06-27T15:18:00",
        severity="high",
        status="active",
    ),
    RawEvent(
        id=4,
        source="facilities_alert",
        category="power",
        title="Power Outage",
        message="Partial power outage reported in the Engineering Building.",
        location_name="Engineering Building",
        latitude=42.8178,
        longitude=-73.9285,
        timestamp="2026-06-27T15:30:00",
        severity="high",
        status="active",
    ),
    RawEvent(
        id=5,
        source="it_services",
        category="network",
        title="Wi-Fi Degradation",
        message="Campus Wi-Fi latency is higher than normal in the library.",
        location_name="Library",
        latitude=42.8169,
        longitude=-73.9298,
        timestamp="2026-06-27T15:40:00",
        severity="low",
        status="monitoring",
    ),
]